name: PHP Composer

on:
  schedule:
  - cron: "0 17 * * *"
    
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${GIT_NAME}
          git config --global user.email ${GIT_EMAIL}

          # Pass the --rebase-merges option to git rebase by default
          git config --global pull.rebase merges

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          # Add the repo which you forked to the remote and name it as "upstream"
          git remote add upstream ${REPO_FORK}

          # Fetch the upstream branches to local
          git fetch upstream

          # Merge changes
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
        # Change the below to your settings
        env:
          GIT_NAME: ${{ secrets.GitName }}
          GIT_EMAIL: ${{ secrets.GitEmail }}
          REPO_FORK: https://github.com/codeigniter4/framework.git
